"""Regenerate native stroke-font advance measurements using KiCad's pcbnew module.

Run with KiCad 10's Python, from the repository root. Only numeric measurements
are stored; the exporter does not bundle glyph outlines or require KiCad at runtime.
"""
from pathlib import Path

import pcbnew

board = pcbnew.BOARD()
text = pcbnew.PCB_TEXT(board)
text.SetTextSize(pcbnew.VECTOR2I(pcbnew.FromMM(1), pcbnew.FromMM(1)))
text.SetTextThickness(pcbnew.FromMM(0.1))
runs = []
for codepoint in range(32, 0x10000):
    if 0xD800 <= codepoint <= 0xDFFF:
        advance = 18  # Surrogates are not Unicode scalar values; use '?'.
    else:
        char = chr(codepoint)
        text.SetText(char)
        single = text.GetBoundingBox().GetWidth()
        text.SetText(char * 2)
        double = text.GetBoundingBox().GetWidth()
        # The difference removes the text box's trailing margin and stroke.
        advance = round(pcbnew.ToMM(double - single) * 21)
    if runs and runs[-1][1] == advance:
        runs[-1][0] = codepoint
    else:
        runs.append([codepoint, advance])

output = Path("lib/pcb/stages/utils/kicad-stroke-font-advances.ts")
encoded = [f"{end}:{advance}" for end, advance in runs]
lines = [" ".join(encoded[i:i + 12]) for i in range(0, len(encoded), 12)]
output.write_text(
    "// Generated by scripts/measure-kicad-stroke-font.py with KiCad 10.0.0.\n"
    "// Entries: inclusive final BMP codepoint : glyph advance in 1/21-em units.\n"
    "// Numeric measurements only, not glyph outlines. Do not edit by hand.\n"
    "export const kicadStrokeFontAdvances = `\n"
    + "\n".join(lines)
    + '\n`\n  .trim()\n  .split(/\\s+/)\n  .map((run) => run.split(":").map(Number))\n'
)
print(f"Measured {len(runs)} runs with KiCad {pcbnew.Version()}: {output}")
