import type { CircuitJson } from "circuit-json"
import {
  ConverterStage,
  type ConverterContext,
  type KicadLibraryOutput,
} from "../../types"

/**
 * Generates the library table files (fp-lib-table and sym-lib-table) and
 * collects model files to finalize the library output.
 */
export class GenerateLibraryTablesStage extends ConverterStage<
  CircuitJson,
  KicadLibraryOutput
> {
  override _step(): void {
    const libraryName = this.ctx.libraryName ?? "tscircuit"
    const fpLibraryName = this.ctx.fpLibraryName ?? "tscircuit"
    const footprintEntries = this.ctx.footprintEntries ?? []

    // Collect all 3D model source paths from footprints
    const model3dSourcePathsSet = new Set<string>()
    for (const fp of footprintEntries) {
      for (const modelPath of fp.model3dSourcePaths) {
        model3dSourcePathsSet.add(modelPath)
      }
    }

    // Generate library tables
    const fpLibTableString = this.generateFpLibTable(fpLibraryName)
    const symLibTableString = this.generateSymLibTable(libraryName)

    // Ensure library output is initialized
    if (!this.ctx.libraryOutput) {
      this.ctx.libraryOutput = {
        kicadSymString: "",
        symbols: [],
        footprints: [],
        fpLibTableString: "",
        symLibTableString: "",
        model3dSourcePaths: [],
      }
    }

    // Finalize the library output
    this.ctx.libraryOutput.footprints = footprintEntries
    this.ctx.libraryOutput.fpLibTableString = fpLibTableString
    this.ctx.libraryOutput.symLibTableString = symLibTableString
    this.ctx.libraryOutput.model3dSourcePaths = Array.from(
      model3dSourcePathsSet,
    )

    this.finished = true
  }

  private generateFpLibTable(fpLibraryName: string): string {
    return `(fp_lib_table
  (version 7)
  (lib (name "${fpLibraryName}") (type "KiCad") (uri "\${KIPRJMOD}/${fpLibraryName}.pretty") (options "") (descr "Generated by circuit-json-to-kicad"))
)
`
  }

  private generateSymLibTable(libraryName: string): string {
    return `(sym_lib_table
  (version 7)
  (lib (name "${libraryName}") (type "KiCad") (uri "\${KIPRJMOD}/${libraryName}.kicad_sym") (options "") (descr "Generated by circuit-json-to-kicad"))
)
`
  }

  override getOutput(): KicadLibraryOutput {
    return this.ctx.libraryOutput!
  }
}
